<?php
include('../lib/Db.php');
include('../models/Usuario.php');
include('../models/Ubicacion.php');
include('../models/Documento.php');

$documento_obj = new Documento($link);
// $documento_obj->documento = '34';
// $documento_obj->detalle = 'carrito rojo de carrera';
// $documento_obj->tipo_documento = '1';
// $documento_obj->fecha = '2017-08-10';
// $documento_obj->codigo_usuario = '1';
// $documento_obj->fecha_registro = '2017-07-30';
// $documento_obj->documento_afectado = '1';
// $documento_obj->valor = '500';
// $documento_obj->monto = '2000';
// $documento_obj->hora = '8:50';
// $documento_obj->codigo_usuario_secundario = '7';
// $documento_obj->estado = '1';
// $documento_obj->comentario = 'nuevecito papush';
// $documento_obj->referencia = '08954564987797889';
// $documento_obj->foto = 'http://localhost/Carfax/public/img/ferrary.jpg';
// $documento_obj->update($documento_obj);
$filtros = array();
$filtros["tipo_documento"] = $_GET['tipo_documento'];
$filtros['vehiculo'] = $_GET['vehiculo'];
$filtros['desde'] = $_GET['desde'];
$filtros['hasta'] = $_GET['hasta'];
var_dump($documento_obj->consulta_filter($filtros));
die();